#No olvides codificar en base64 tu SecretAccessKey  echo tu-clave | base64
apiVersion: v1
data:
  AWS_SECRET_ACCESS_KEY: { aws-secret-key | base64 }
kind: Secret
metadata:
  name: aws-certmanager-credentials
  namespace: cert-manager
type: Opaque
