#https://cert-manager.io/docs/configuration/acme/dns01/route53/
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cluster-issuer
  namespace: cert-manager
spec:
  acme:
    privateKeySecretRef:
      name: issuer-letsencrypt
    email: tu-email@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - selector: {}
        dns01:
          route53:
            region: us-east-1
            accessKeyID: { aws-accesskey }
            secretAccessKeySecretRef:
              name: aws-certmanager-credentials
              key: AWS_SECRET_ACCESS_KEY
