apiVersion: v1
kind: Service
metadata:
  labels:
    common.k8s.elastic.co/type: enterprise-search
    enterprisesearch.k8s.elastic.co/name: quickstart
  name: quickstart-ent-http-external
spec:
  type: NodePort
  ports:
    - name: https
      port: 3002
      protocol: TCP
      targetPort: 3002
      nodePort: 30002
  selector:
    common.k8s.elastic.co/type: enterprise-search
    enterprisesearch.k8s.elastic.co/name: quickstart
  sessionAffinity: None
